name: Build Image and Deploy
on:
  push:
    branches: master

jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login Harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.ar2ro.io
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Build and push to harbor
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          harbor.ar2ro.io/destinyarena/authorization:latest
          harbor.ar2ro.io/destinyarena/authorization:v1.0.0
    - name: Checkout Helm Repo
      uses: actions/checkout@v2
      with:
        repository: destinyarena/helm-charts
    - name: Installs yq
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
    - name: Update the Helm Chart values.yaml
      run: |
        yq w -i values.yaml authorization.image.tag v1.0.0
    - name: Commit and Push
      uses: EndBug/add-and-commit@v5
      with:
        author_name: "github-actions"
        author_email: "github-actions@github.com"
        message: "Updated Tag to v1.0.0"
      env:
        GITHUB_TOKEN: ${{ secrets.DESTINYARENA_ACTIONS }}
